const FAILD = "Faild";
const FAILD_CODE = 404;
const UNAUTHORIZED = "UNAUTHORIZED";
const UNAUTHORIZED_CODE = 401;
const SUCCESS = "Success";
const SUCCESS_CODE = 200;

export default {
  FAILD,
  FAILD_CODE,
  UNAUTHORIZED,
  UNAUTHORIZED_CODE,
  SUCCESS,
  SUCCESS_CODE,
};
